### ISSUE TITLE
Introduction to CSS3 worksheet: Suggestion for the #special tag CSS

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#2]
The CSS for the "special" tag under the **Identifiers** heading in the Introduction to CSS3 worksheet works but is a bit boring. Perhaps something like this would be better for demonstration purposes rather than just changing the font size?

``` css
#special {
    font-size: 0.8em;
    color: yellowgreen;
    font-style: italic;
    border-left: 2px solid black;
    margin-left: 40px;
    padding-left: 10px;
}
```
