### ISSUE TITLE
CSS code already present

### ISSUE THREAD

**Issue by JoseUusitalo** [covcom/205CDE#4]
Near the end of the worksheet we are asked to copy the following CSS into **targetstyles.css** but the given CSS code is already present in the file.

``` css
ol > li {
    color: green;    
}

ul li ul {
    font-weight: bold;
}

ul li ul li ul {
    color: blue;
}
```
